# Generated by Django 3.1.3 on 2023-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('pname', models.TextField()),
                ('releasedate', models.DateTimeField()),
                ('runningtime', models.IntegerField(default=0)),
                ('rprice', models.IntegerField(default=0)),
                ('pprice', models.IntegerField(default=0)),
            ],
        ),
    ]
