# Generated by Django 3.1.3 on 2023-04-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.TextField(),
        ),
    ]
