# Generated by Django 3.1.3 on 2023-04-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20230405_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='releasedate',
            field=models.DateField(),
        ),
    ]
