# Generated by Django 3.1.3 on 2023-04-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20230407_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rprice',
        ),
    ]
