# Generated by Django 3.1.3 on 2023-04-12 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_product_rprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_date', models.DateTimeField()),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_pname', to='sales.product')),
                ('pprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_pprice', to='sales.product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_type', to='sales.product')),
            ],
        ),
    ]
