# Generated by Django 3.1.3 on 2023-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinfo',
            name='pname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salesinfo',
            name='pprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesinfo',
            name='type',
            field=models.TextField(),
        ),
    ]
